import{a as y,S as M,i as S}from"./assets/vendor-2618a76b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerpolicy&&(a.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?a.credentials="include":t.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();y.defaults.baseURL="https://pixabay.com/api";const w="41936299-e1d4d29e6aed15564c1848147",s="is-hidden",g=new M(".gallery-item a",{captionsData:"alt",captionDelay:250}),r={form:document.querySelector(".form"),input:document.querySelector(".search-input"),button:document.querySelector(".search-btn"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn")};let d="",i=1,m=0;r.form.addEventListener("submit",B);async function B(e){if(e.preventDefault(),r.gallery.innerHTML="",i=1,r.loadMoreBtn.classList.add(s),d=r.input.value.trim(),!d){u("Please, enter search term!");return}try{const{hits:o,totalHits:n}=await p(d);m=Math.ceil(n/40),h(o),g.refresh(),o.length>0?(r.loadMoreBtn.classList.remove(s),r.loadMoreBtn.addEventListener("click",k)):(r.loadMoreBtn.classList.add(s),u("Sorry, there are no images matching your search query. Please, try again!")),f(!1)}catch(o){console.log(o)}finally{r.form.reset(),i===m&&(r.loadMoreBtn.classList.add(s),u("We're sorry, but you've reached the end of search results!"))}}async function k(){i+=1;try{f(!0),r.loadMoreBtn.classList.add(s);const{hits:e}=await p(d,i);h(e),g.refresh(),f(!1),q(),r.loadMoreBtn.classList.remove(s)}catch(e){console.log(e)}finally{i===m&&(r.loadMoreBtn.classList.add(s),u("We're sorry, but you've reached the end of search results!"))}}async function p(e,o=1){return f(!0),(await y.get("/",{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:o}})).data}function h(e){const o=e.map(({webformatURL:n,largeImageURL:c,tags:t,likes:a,views:l,comments:L,downloads:b})=>`
          <li class="gallery-item">
    <a class="gallery-link" href="${c}">
      <img
        class="gallery-img"
        src="${n}"
        alt="${t}"
      />
      <p class="gallery-inf">
      Likes: <span class="img-stat">${a}</span> 
      Views: <span class="img-stat">${l}</span> 
      Comments: <span class="img-stat">${L}</span> 
      Downloads: <span class="img-stat">${b}</span></p>
    </a>
  </li>`).join("");r.gallery.insertAdjacentHTML("beforeend",o)}function u(e){S.show({class:"error-circul",position:"topRight",icon:"error-circul",message:e,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function q(){const e=document.querySelector(".gallery-link");if(e){const o=e.getBoundingClientRect();window.scrollBy({top:o.height*2,left:0,behavior:"smooth"})}}function f(e=!0){r.loader.style.display=e?"inline-block":"none",r.button.disabled=e}
//# sourceMappingURL=commonHelpers.js.map
