import{a as g,S as k,i as B}from"./assets/vendor-2618a76b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function l(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerpolicy&&(a.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?a.credentials="include":t.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function d(t){if(t.ep)return;t.ep=!0;const a=l(t);fetch(t.href,a)}})();g.defaults.baseURL="https://pixabay.com/api";const p="41936299-e1d4d29e6aed15564c1848147",n="is-hidden",h=new k(".gallery-item a",{captionsData:"alt",captionDelay:250}),r={form:document.querySelector(".form"),input:document.querySelector(".search-input"),button:document.querySelector(".search-btn"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn")};let u="",c=1,m=0;r.form.addEventListener("submit",S);async function S(e){if(e.preventDefault(),r.gallery.innerHTML="",c=1,r.loadMoreBtn.classList.add(n),u=r.input.value.trim(),!u){s("Please, enter search term!");return}if(!p.trim()){s("API key is missing or invalid.");return}try{const{hits:o,totalHits:l}=await L(u);m=Math.ceil(l/40),b(o),h.refresh(),o.length>0?(r.loadMoreBtn.classList.remove(n),r.loadMoreBtn.removeEventListener("click",y),r.loadMoreBtn.addEventListener("click",y)):(r.loadMoreBtn.classList.add(n),s("Sorry, there are no images matching your search query. Please, try again!")),f(!1)}catch(o){console.log(o),s("An error occurred. Please try again later.")}finally{r.form.reset(),c===m&&(r.loadMoreBtn.classList.add(n),s("We're sorry, but you've reached the end of search results!"))}}async function y(){c+=1;try{f(!0),r.loadMoreBtn.classList.add(n);const{hits:e}=await L(u,c);b(e),h.refresh(),f(!1),w(),r.loadMoreBtn.classList.remove(n)}catch(e){console.log(e),s("An error occurred. Please try again later.")}finally{c===m&&(r.loadMoreBtn.classList.add(n),s("We're sorry, but you've reached the end of search results!"))}}async function L(e,o=1){return f(!0),(await g.get("/",{params:{key:p,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:o}})).data}function b(e){const o=e.map(({webformatURL:l,largeImageURL:d,tags:t,likes:a,views:i,comments:M,downloads:v})=>`
          <li class="gallery-item">
    <a class="gallery-link" href="${d}">
      <img
        class="gallery-img"
        src="${l}"
        alt="${t}"
      />
      <p class="gallery-inf">
      Likes: <span class="img-stat">${a}</span> 
      Views: <span class="img-stat">${i}</span> 
      Comments: <span class="img-stat">${M}</span> 
      Downloads: <span class="img-stat">${v}</span></p>
    </a>
  </li>`).join("");r.gallery.insertAdjacentHTML("beforeend",o)}function s(e){B.show({class:"error-circul",position:"topRight",icon:"error-circul",message:e,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function w(){const e=document.querySelector(".gallery-link");if(e){const o=e.getBoundingClientRect();window.scrollBy({top:o.height*2,left:0,behavior:"smooth"})}}function f(e=!0){r.loader.style.display=e?"inline-block":"none",r.button.disabled=e}
//# sourceMappingURL=commonHelpers.js.map
