import{a as g,S as B,i as k}from"./assets/vendor-2618a76b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function l(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerpolicy&&(a.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?a.credentials="include":t.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(t){if(t.ep)return;t.ep=!0;const a=l(t);fetch(t.href,a)}})();g.defaults.baseURL="https://pixabay.com/api";const p="41936299-e1d4d29e6aed15564c1848147",s="is-hidden",h=new B(".gallery-item a",{captionsData:"alt",captionDelay:250}),r={form:document.querySelector(".form"),input:document.querySelector(".search-input"),button:document.querySelector(".search-btn"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more-btn")};let f="",i=1,m=0;r.form.addEventListener("submit",S);async function S(e){if(e.preventDefault(),r.gallery.innerHTML="",i=1,r.loadMoreBtn.classList.add(s),f=r.input.value.trim(),!f){n("Please, enter search term!");return}if(!p.trim()){n("API key is missing or invalid.");return}try{d(!0);const{hits:o,totalHits:l}=await L(f);m=Math.ceil(l/40),b(o),h.refresh(),r.loadMoreBtn.removeEventListener("click",y),o.length>0?(r.loadMoreBtn.classList.remove(s),r.loadMoreBtn.addEventListener("click",y)):(r.loadMoreBtn.classList.add(s),n("Sorry, there are no images matching your search query. Please, try again!")),r.form.reset()}catch(o){console.log(o),n("An error occurred. Please try again later.")}finally{d(!1),i===m&&(r.loadMoreBtn.classList.add(s),n("We're sorry, but you've reached the end of search results!"))}}async function y(){if(i>m){r.loadMoreBtn.classList.add(s);return}i+=1;try{d(!0),r.loadMoreBtn.classList.add(s);const{hits:e}=await L(f,i);b(e),h.refresh(),d(!1),w(),r.loadMoreBtn.classList.remove(s)}catch(e){console.log(e),n("An error occurred. Please try again later.")}finally{i===m&&(r.loadMoreBtn.classList.add(s),n("We're sorry, but you've reached the end of search results!"))}}async function L(e,o=1){return d(!0),(await g.get("/",{params:{key:p,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:o}})).data}function b(e){const o=e.map(({webformatURL:l,largeImageURL:u,tags:t,likes:a,views:c,comments:M,downloads:v})=>`
          <li class="gallery-item">
    <a class="gallery-link" href="${u}">
      <img
        class="gallery-img"
        src="${l}"
        alt="${t}"
      />
      <p class="gallery-inf">
      Likes: <span class="img-stat">${a}</span> 
      Views: <span class="img-stat">${c}</span> 
      Comments: <span class="img-stat">${M}</span> 
      Downloads: <span class="img-stat">${v}</span></p>
    </a>
  </li>`).join("");r.gallery.insertAdjacentHTML("beforeend",o)}function n(e){k.show({class:"error-circul",position:"topRight",icon:"error-circul",message:e,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function w(){const e=document.querySelector(".gallery-link");if(e){const o=e.getBoundingClientRect();window.scrollBy({top:o.height*2,left:0,behavior:"smooth"})}}function d(e=!0){r.loader.style.display=e?"inline-block":"none",r.button.disabled=e}
//# sourceMappingURL=commonHelpers.js.map
